name: Build and Deploy Check
on:
  pull_request:
    branches: [main]

jobs:
  build-and-deploy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy check
        run: |
          if [ $? -eq 0 ]; then
            echo "Build successful! PR is deployable."
            exit 0
          else
            echo "Build failed! PR is not deployable."
            exit 1
          fi

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            You should see check mark(ok/not-ok), If Something went wrong while running `npm run build` command,
            please try running on your local check, if found any issue on that, please fix.
